# Thanks to jtilly (https://github.com/jtilly/R-travis-container-example/blob/master/.travis.yml)

language: r
dist: trusty
sudo: false

branches:
  only:
    - master

# cache local packages
cache: packages

# install the package and dependencies:
# - update all installed packages
# - install package with dependencies
install:
  - Rscript -e 'update.packages(ask = FALSE)'
  - Rscript -e 'devtools::install_deps(pkg = ".", dependencies = TRUE)'

# Build and check package
script:
  - R CMD build . --no-build-vignettes --no-manual
  - PKG_FILE_NAME=$(ls -1t *.tar.gz | head -n 1)
  - R CMD check "${PKG_FILE_NAME}" --no-build-vignettes --no-manual --as-cran 

# build package site
after_success:
  - travis_wait Rscript -e "pkgdown::build_site()"

# deploy site to gh-pages branch  
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  on:
    branch: master
  local_dir: docs
  keep-history: false
  allow-empty-commit: false

# send email if any changes
notifications:
  email:
    on_success: change
    on_failure: change

